### ISSUE TITLE
A "Hello World" example in Wiki would be nice

### ISSUE THREAD

**Issue by grahamreeds** [doe300/VC4CL#46]
A Hello-World example program would be helpful for those struggling to get to grips with it (and OpenCL in general).

**Comment by doe300** [comment]
As I see it, there is no short and simple "Hello World" example I can give to showcase OpenCL, since it has  a complex structure with a rather steep initial learning curve.
But for simple OpenCL examples, google is your friend. Or take a look at:

* https://github.com/Dakkers/OpenCL-examples
* https://github.com/rsnemmen/OpenCL-examples (actually has a 200-lines hello world example)
* https://www.eriksmistad.no/getting-started-with-opencl-and-gpu-computing/
* Or for a more in-depth and lecture-like introduction: http://sa10.idav.ucdavis.edu/
