### ISSUE TITLE
DepthMap (StereoBM) acceleration

### ISSUE THREAD

**Issue by realizator** [doe300/VC4CL#50]
Hello @doe300!

User Gavinmc42 on Raspberry Pi forum (https://www.raspberrypi.org/forums/viewtopic.php?f=37&t=216940&p=1408611#p1408600) recommended me to contact you.

I'm a hardware developer, and our team did a stereoscopic camera based on Raspberry Pi Compute Module 3 (http://stereopi.com).

For OpenCV and ROS implementation Depth Map is a critical thing, so I'm looking for ways to increase Pi performance in this task. So I have some questions:

1. How do you think, if VC4CL is applicable for this function (StereoBM, FindStereoCorrespondenceBM)? As for StereoSGBM it looks like this function is far from real-time, but may be you have some ideas or suggestions here.
2. I plan to use H264 encoder for depth map acceleration. Yes, DM resolution will be smaller in this case (~16 times), but the main ARM kernels will not be loaded with this approach. Have you plan to use H264 encoder in some ways in your VC4CL?
3. StereoPi can be used not only in stereoscopic setup, but also for work with two independent cameras simultaneously (like back-to-back for 360 panoramas with 200 degree fisheye cameras, or with two different cameras like classic Pi camera and NoIR edition). If you think these tasks can be accelerated too - I will be appreciate for your ideas.
4. If these tasks are interesting for you, I can send you one of our boards for you to be able to conduct all experiments you need.

Regards,
Eugene

**Comment by doe300** [comment]
1. At this time, VC4CL will probably not be able to compute those (or any) OpenCV functionalities correctly, since it still lacks accuracy especially for mathematical functions.
2. H264 is a video codec and OpenCL (which VC4CL implements) does not support videos at all. Even if I deviate from the OpenCL standard, I have no idea how to talk to any video-encoding hardware parts. You may be able to do this yourself using the [MMAL](https://github.com/raspberrypi/firmware/tree/master/opt/vc/include/interface/mmal) or [OpenMAX](https://github.com/raspberrypi/firmware/tree/master/opt/vc/include/IL) interfaces, since this is - AFAIK - the way to go.
3. Stitching together those images (e.g. to a 360° view for panorama or to some kind of enhanced image for "normal" and NoIR camera) should most definitively be done (at least partially) on the GPU. But the software to use here depends on the performance needed and the exact tasks to perform. Maybe you'll need to write direct GPU assembler or can use the existing OpenGL implementation.
4. I don't think VC4CL as a software will be particularly useful for your use-case (I could be wrong though), but I will try to be of help where I can.
